version: '3'
networks:
  openhim:
    external: true
services:
  backend:
    restart: always
    container_name: ${HOST}
    networks:
      - openhim
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ${ADX_LOGISTICS_DIR}:/usr/src/app/adx_logistics